### PR TITLE
Change "Add File" to "Import File" throughout.  English improvements.

### LINKED ISSUE #5: Update to match "Add File" -> "Import File" change in PhaserEditor2D-v3
(not sure if there's a better way to track this.)

### PR DESCRIPTION
**Pull request by michaelgundlach**
If this looks good to you, I'll also redo the images (I didn't want to take the time if you don't agree with any of the UI text :) )

Fixes #5

### CODE REVIEW

**Comment by PhaserEditor2D** [comment]
Hey! Thanks for getting the time to make the docs more clear! Nice work!

**Comment by PhaserEditor2D** [comment]
Hi @michaelgundlach! I didn't notice that you changed the name of some files. Please, if you can roll back the names of the files. For example, `import-from-main-toolbar` to previous `add-file-with-add-button`. The problem is that it now will have a different URL and may break some references from external sites. You can change the title of chapters, but keep the same file name when possible.

Again, nice work! Thanks!

**Comment by michaelgundlach** [comment]
Good point! See #9.

**Comment by michaelgundlach** [comment]
@PhaserEditor2D Where can I find the Dragon Demo you use in your screenshots, so I can make the updated ones?

**Comment by PhaserEditor2D** [comment]
Take it here: [Flying dragon.zip](https://github.com/PhaserEditor2D/PhaserEditor-v3-docs/files/7824843/Flying.dragon.zip)

**Pull request merged**
